# 언어(플랫폼) 선택
language: generic

# 관리자 권한 갖기
sudo: required

#도커 환경 구성
services:
  - docker
# 스크립트를 실행할 수 있는 환경 구성
before_install:
  - docker build -t dk/docker-multi-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true dk/docker-multi-app npm run test

after_success:
  # 각각의 이미지 빌드
  - docker build -t dk/docker-frontend ./frontend
  - docker build -t dk/docker-backend ./backend
  - docker build -t dk/docker-nginx ./nginx

  # 도커 허브에 로그인
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  # 빌드된 이미지들을 도커 허브에 푸시
  - docker push dk/docker-frontend
  - docker push dk/docker-backend
  - docker push dk/docker-nginx



deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-multi-app"
  env: "DockerMultiApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
  bucket_path: "docker-fullstack-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY