language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t dokyung94/docker-multi-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true dokyung94/docker-multi-app npm test

after_success:
  - docker build -t dokyung94/docker-frontend ./frontend
  - docker build -t dokyung94/docker-backend ./backend
  - docker build -t dokyung94/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dokyung94/docker-frontend
  - docker push dokyung94/docker-backend
  - docker push dokyung94/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-multi-app
  env: Dockermultiapp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-990079660208
  bucket_path: docker-multi-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY